---
- hosts: imageme_nodes
  become: yes
  vars: 
    - SEARCH_ENGINE_ID: 006879359584856769921:rplfy3clmho
    - GOOGLE_CLOUD_API_KEY: AIzaSyDLLC1pqOxkWA8jUjM-Cfwbl_13Sh_2t98
  tasks:
    - name: "install git"
      yum:
        name: git
        state: latest
    - name: "clone repo"
      git: 
        repo: https://github.com/jkanclerz/google-search-python.git
        version: master
        dest: /home/ec2-user/imageMe
    - name: "set environment variable (SEARCH_ENGINE_ID)"
      shell: "echo 'export SEARCH_ENGINE_ID='{{SEARCH_ENGINE_ID}}'' >> .bashrc"
    - name: "set environment variable (GOOGLE_CLOUD_API_KEY)"
      shell: "echo 'export GOOGLE_CLOUD_API_KEY='{{GOOGLE_CLOUD_API_KEY}}'' >> .bashrc"
    - name: "Create directory"
      file:
        path: /home/ec2-user/bin
        state: directory
    - name: "Copy script file and change permissions"
      copy:
        src: ./templates/imageMe.sh
        dest: /home/ec2-user/bin/imageMe.sh
        mode: a+x